from typing import NamedTuple, Callable, Dict, List, Optional
# from BaseClasses import CollectionState

er_static_connections: Dict[str, List[str]] = {
    "Menu": ["dog house west"],
    "lighthouse land": ["lighthouse water"],
    "boat land": ["boat water"],
    "sword main": ["sword bushes", "sword water"],
    "2crab land": ["2crab water", "2crab tree exit"],
    "dolphin land": ["dolphin water", "dolphin bushes"],
    "desert beach land": ["desert beach water"],
    "coffee shop outside": ["coffee shop pot stairs", "coffee shop water"],
    "coffee shop upper beach": ["coffee shop water"],
    "plant main": ["plant bushes"],
    "dog house west": ["dog house river"],
    "dog house river": ["dog house east"],
    "dog house west": ["dog house bushes"],
    "quicksand main": ["quicksand left tree", "quicksand right tree"],
    "boattree main": ["boattree box", "boattree river"],
    "camera river south": ["camera river north", "camera river wet"],
    "camera river north": ["camera river wet"],
    "camera house outside": ["camera house tree"],
    "3crab main": ["3crab trees"],
    "sewer island mainland": ["sewer island water"],
    "throwcheck land": ["throwcheck water", "throwcheck box"],
    "arena main": ["arena tree north", "arena tree west"],
    "bridge switch right": ["bridge switch water"],
    "bridge switch left": ["bridge switch water"],
    "bridge right": ["bridge water"],
    "bridge left": ["bridge water", "bridge right"],
    "mine entrance left": ["mine entrance river"],
    "factory reception main": ["factory reception east"],
    "factory cooler west": ["factory cooler east"],
    "factory loading lower main": ["factory loading lower shortcut"],
    "shoe shop outside": ["shoe shop shortcut"],
    "mine entrance bombs": ["mine entrance pipe"],
    "mine main": ["mine main box"],
    "sewer main right": ["sewer main left"],
    "sewer bat arena": ["sewer bat gate"],
    "grinder south": ["grinder main"],
    "grinder east": ["grinder main"],
    "factory machine generator": ["factory machine catwalk"],
    "miner chest belts": ["miner chest pipe entrance"],
}

er_regions: List[str] = [
    "Menu", "lighthouse water", "lighthouse land", "lighthouse lookout",
    "boat water", "boat land", "sword bushes", "sword main", "sword water",
    "2crab land", "2crab water", "2crab tree exit", "dolphin land",
    "dolphin water", "dolphin bushes", "desert beach water",
    "desert beach land", "coffee shop outside", "coffee shop pot stairs",
    "coffee shop water", "coffee shop upper beach", "above lighthouse land",
    "above lighthouse water", "plant bushes", "plant main", "dog house west",
    "dog house east", "dog house river", "dog house bushes", "glove outside",
    "watering can", "quicksand main", "quicksand left tree",
    "quicksand right tree", "bull room", "boattree main", "boattree box",
    "boattree river", "boattree east", "key room", "camera path",
    "camera river north", "camera river south", "camera river wet",
    "camera river lookout", "camera house outside", "camera house tree",
    "3crab main", "3crab trees", "3crab north water", "3crab south water",
    "3crab land path", "sewer island", "sewer island water",
    "sewer island mainland", "throwcheck land", "throwcheck water",
    "throwcheck box", "diver room", "wallet room", "bone room", "marys house",
    "arena tree north", "arena tree west", "arena main", "crowroom",
    "tree resident", "bridge switch lookout", "bridge switch right",
    "bridge switch left", "bridge switch water", "bridge right", "bridge left",
    "bridge water", "hotel outside", "mine entrance right",
    "mine entrance left", "mine entrance river", "poison river corner",
    "factory reception main", "factory reception east", "factory queue",
    "factory cooler west", "factory cooler east", "factory toilet",
    "factory central", "factory drill", "factory loading upper",
    "factory loading lower main", "factory loading lower shortcut",
    "factory loading deadend", "factory loading desert", "shoe shop outside",
    "shoe shop shortcut", "temple outside", "desert RV main",
    "desert RV corner", "desert right cliffs", "desert left cliffs",
    "Overworld", "RV house", "shoe shop inside", "hotel reception",
    "hotel backroom", "camera house inside", "waterfall cave",
    "dog house inside", "coffee shop inside", "lighthouse inside",
    "island house", "megasword upper", "megasword lower", "underground house",
    "glove inside", "shoe shop downstairs", "temple main", "temple octopus",
    "temple tentacle", "temple heart", "temple firebat test",
    "temple firebat chest", "temple coin test", "temple coin chest",
    "hotel room", "mine entrance path", "mine entrance bombs",
    "mine entrance pipe", "mine main", "mine main box", "dog house basement",
    "snake east", "snake west", "sewer main right", "sewer main left",
    "sewer bat arena", "sewer bat gate", "sewer upper", "sewer tentacle",
    "island teleporter", "submarine", "teleporter switch1", "teleporter maze",
    "teleporter tentacle", "grinder south", "grinder east", "grinder main",
    "factory machine generator", "factory machine catwalk",
    "factory switch test", "factory mega entrance", "factory snakehall",
    "miner chest belts", "miner chest pipe entrance", "miner chest pipe L",
    "trophy pipe hall", "tent room main", "tent room pipe O",
    "tent room pipe I", "trophy maze lower main", "trophy maze lower hall",
    "trophy maze upper main", "trophy maze upper hall", "trophy maze deadend",
    "trophy room",
]

er_entrances: List[List[any]] = [
    ["lighthouse water upper west", "lighthouse water", False, "water",
        "rom7_10", -1, -1],
    ["lighthouse water upper north", "lighthouse water", False, "water",
        "rom7_10", -1, -1],
    ["lighthouse water upper east", "lighthouse water", False, "water",
        "rom7_10", -1, -1],
    ["lighthouse water lower west", "lighthouse water", False, "water",
        "rom7_11", -1, -1],
    ["lighthouse water lower south", "lighthouse water", False, "water",
        "rom7_11", -1, -1],
    ["lighthouse water lower east", "lighthouse water", False, "water",
        "rom7_11", -1, -1],
    ["lighthouse upper door", "lighthouse lookout", True, "land",
        "rom7_10", 93, 128],
    ["lighthouse lower door", "lighthouse land", False, "land",
        "rom7_11", 128, 128],
    ["lighthouse bridge", "lighthouse land", False, "land",
        "rom7_11", 304, 112],
    ["boat water south", "boat water", False, "water",
        "rom8_11", -1, -1],
    ["boat water east", "boat water", False, "water",
        "rom8_11", -1, -1],
    ["boat water north", "boat water", False, "water",
        "rom8_11", -1, -1],
    ["boat water west", "boat water", False, "water",
        "rom8_11", -1, -1],
    ["boat land north", "boat land", False, "land",
        "rom8_11", -1, -1],
    ["boat land east", "boat land", False, "land",
        "rom8_11", -1, -1],
    ["boat land west", "boat land", False, "land",
        "rom8_11", -1, -1],
    ["sword west", "sword bushes", False, "land",
        "rom9_11", -1, -1],
    ["sword east", "sword main", False, "land",
        "rom9_11", -1, -1],
    ["sword water east", "sword water", False, "water",
        "rom9_11", -1, -1],
    ["sword water south", "sword water", False, "water",
        "rom9_11", -1, -1],
    ["sword water west", "sword water", False, "water",
        "rom9_11", -1, -1],
    ["2crab land east", "2crab land", False, "land",
        "rom10_11", -1, -1],
    ["2crab land west", "2crab land", False, "land",
        "rom10_11", -1, -1],
    ["2crab land north main", "2crab land", False, "land",
        "rom10_11", -1, -1],
    ["2crab land north river", "2crab water", False, "water",
        "rom10_11", -1, -1],
    ["2crab land water east", "2crab water", False, "water",
        "rom10_11", -1, -1],
    ["2crab land water south", "2crab water", False, "water",
        "rom10_11", -1, -1],
    ["2crab land water west", "2crab water", False, "water",
        "rom10_11", -1, -1],
    ["2crab land north side", "2crab tree exit", False, "land",
        "rom10_11", -1, -1],
    ["dolphin land west", "dolphin land", False, "land",
        "rom11_11", -1, -1],
    ["dolphin bushes", "dolphin bushes", False, "land",
        "rom11_11", -1, -1],
    ["dolphin water east", "dolphin water", False, "water",
        "rom11_11", -1, -1],
    ["dolphin water south", "dolphin water", False, "water",
        "rom11_11", -1, -1],
    ["dolphin water west", "dolphin water", False, "water",
        "rom11_11", -1, -1],
    ["desert beach water south", "desert beach water", False, "water",
        "rom12_11", -1, -1],
    ["desert beach water west", "desert beach water", False, "water",
        "rom12_11", -1, -1],
    ["desert beach land east", "desert beach land", False, "land",
        "rom12_11", -1, -1],
    ["desert beach land south", "desert beach land", False, "land",
        "rom12_11", -1, -1],
    ["coffee shop outside north", "coffee shop outside", False, "land",
        "rom8_10", -1, -1],
    ["coffee shop outside east", "coffee shop outside", False, "land",
        "rom8_10", -1, -1],
    ["coffee shop outside south", "coffee shop outside", False, "land",
        "rom8_10", -1, -1],
    ["coffee shop door", "coffee shop outside", False, "land",
        "rom8_10", -1, -1],
    ["coffee shop pot stairs", "coffee shop pot stairs", False, "land",
        "rom8_10", -1, -1],
    ["coffee shop water north", "coffee shop water", False, "water",
        "rom8_10", -1, -1],
    ["coffee shop water west", "coffee shop water", False, "water",
        "rom8_10", -1, -1],
    ["coffee shop water south", "coffee shop water", False, "water",
        "rom8_10", -1, -1],
    ["coffee shop upper beach", "coffee shop upper beach", False, "land",
        "rom8_10", -1, -1],
    ["above lighthouse land", "above lighthouse land", True, "land",
        "rom7_9", -1, -1],
    ["above lighthouse water north", "above lighthouse water", False, "water",
        "rom7_9", -1, -1],
    ["above lighthouse water east upper", "above lighthouse water", False, "water",
        "rom7_9", -1, -1],
    ["above lighthouse water east lower", "above lighthouse water", False, "water",
        "rom7_9", -1, -1],
    ["above lighthouse water south", "above lighthouse water", False, "water",
        "rom7_9", -1, -1],
    ["above lighthouse water west", "above lighthouse water", False, "water",
        "rom7_9", -1, -1],
    ["plant bushes", "plant bushes", False, "land",
        "rom9_10", -1, -1],
    ["plant main", "plant main", False, "land",
        "rom9_10", -1, -1],
    ["dog house door", "dog house west", False, "land",
        "rom10_10", -1, -1],
    ["dog house west", "dog house west", False, "land",
        "rom10_10", -1, -1],
    ["dog house south", "dog house west", False, "land",
        "rom10_10", -1, -1],
    ["dog house east", "dog house east", False, "land",
        "rom10_10", -1, -1],
    ["dog house east lower", "dog house east", False, "land",
        "rom10_10", -1, -1],
    ["dog house river north", "dog house river", False, "water",
        "rom10_10", -1, -1],
    ["dog house river south", "dog house river", False, "water",
        "rom10_10", -1, -1],
    ["dog house bushes", "dog house bushes", False, "land",
        "rom10_10", -1, -1],
    ["glove outside east", "glove outside", False, "land",
        "rom11_10", -1, -1],
    ["glove outside west", "glove outside", False, "land",
        "rom11_10", -1, -1],
    ["glove outside door", "glove outside", False, "land",
        "rom11_10", -1, -1],
    ["watering can", "watering can", True, "land",
        "rom11_10", -1, -1],
    ["quicksand upper east", "quicksand main", False, "land",
        "rom12_9", -1, -1],
    ["quicksand upper west", "quicksand main", False, "land",
        "rom12_9", -1, -1],
    # ["quicksand upper north", "quicksand main", False, "land",
    #     "rom12_9", -1, -1],
    ["quicksand left tree", "quicksand left tree", False, "land",
        "rom12_10", -1, -1],
    ["quicksand right tree", "quicksand right tree", False, "land",
        "rom12_10", -1, -1],
    ["bull room left", "bull room", False, "land",
        "rom11_9", -1, -1],
    ["bull room right", "bull room", False, "land",
        "rom11_9", -1, -1],
    ["boattree main door", "boattree main", False, "land",
        "rom10_9", -1, -1],
    ["boattree main south", "boattree main", False, "land",
        "rom10_9", -1, -1],
    ["boattree box", "boattree box", False, "land",
        "rom10_9", -1, -1],
    ["boattree river north", "boattree river", False, "water",
        "rom10_9", -1, -1],
    ["boattree river south", "boattree river", False, "water",
        "rom10_9", -1, -1],
    ["boattree east", "boattree east", False, "land",
        "rom10_9", -1, -1],
    ["boattree east door", "boattree east", False, "land",
        "rom10_9", -1, -1],
    ["key room", "key room", False, "land",
        "rom9_9", -1, -1],
    ["camera path north", "camera path", False, "land",
        "rom9_9", -1, -1],
    ["camera path east", "camera path", False, "land",
        "rom9_9", -1, -1],
    ["camera river north", "camera river north", False, "land",
        "rom9_8", -1, -1],
    ["camera river south", "camera river south", False, "land",
        "rom9_8", -1, -1],
    ["camera river wet east", "camera river wet", False, "water",
        "rom9_8", -1, -1],
    ["camera river wet west", "camera river wet", False, "water",
        "rom9_8", -1, -1],
    ["camera river lookout", "camera river lookout", False, "land",
        "rom9_8", -1, -1],
    ["camera house outside door", "camera house outside", False, "land",
        "rom9_7", -1, -1],
    ["camera house outside south", "camera house outside", False, "land",
        "rom9_7", -1, -1],
    ["camera house tree", "camera house tree", False, "land",
        "rom9_7", -1, -1],
    ["3crab main east", "3crab main", False, "land",
        "rom8_9", -1, -1],
    ["3crab main south", "3crab main", False, "land",
        "rom8_9", -1, -1],
    ["3crab trees", "3crab trees", False, "land",
        "rom8_9", -1, -1],
    ["3crab north water north", "3crab north water", False, "water",
        "rom8_9", -1, -1],
    ["3crab north water west", "3crab north water", False, "water",
        "rom8_9", -1, -1],
    ["3crab south water west", "3crab south water", False, "water",
        "rom8_9", -1, -1],
    ["3crab south water south", "3crab south water", False, "water",
        "rom8_9", -1, -1],
    ["3crab land path west", "3crab land path", False, "land",
        "rom8_9", -1, -1],
    ["3crab land path south", "3crab land path", False, "land",
        "rom8_9", -1, -1],
    ["sewer island", "sewer island", True, "land",
        "rom8_8", -1, -1],
    ["sewer island water north", "sewer island water", False, "water",
        "rom8_8", -1, -1],
    ["sewer island water east", "sewer island water", False, "water",
        "rom8_8", -1, -1],
    ["sewer island water south", "sewer island water", False, "water",
        "rom8_8", -1, -1],
    ["sewer island water west", "sewer island water", False, "water",
        "rom8_8", -1, -1],
    ["sewer island mainland north", "sewer island mainland", False, "land",
        "rom8_8", -1, -1],
    ["sewer island mainland south", "sewer island mainland", False, "land",
        "rom8_8", -1, -1],
    ["throwcheck land north", "throwcheck land", False, "land",
        "rom8_7", -1, -1],
    ["throwcheck land south", "throwcheck land", False, "land",
        "rom8_7", -1, -1],
    ["throwcheck water south", "throwcheck water", False, "water",
        "rom8_7", -1, -1],
    ["throwcheck water west", "throwcheck water", False, "water",
        "rom8_7", -1, -1],
    ["throwcheck box", "throwcheck box", False, "land",
        "rom8_7", -1, -1],
    ["diver room east", "diver room", False, "land",
        "rom8_6", -1, -1],
    ["diver room south", "diver room", False, "land",
        "rom8_6", -1, -1],
    ["wallet room", "wallet room", False, "land",
        "rom8_5", -1, -1],
    ["wallet room", "wallet room", False, "land",
        "rom8_5", -1, -1],
    ["bone room north", "bone room", False, "land",
        "rom9_4", -1, -1],
    ["bone room east", "bone room", False, "land",
        "rom9_4", -1, -1],
    ["bone room south", "bone room", False, "land",
        "rom9_4", -1, -1],
    ["bone room west", "bone room", False, "land",
        "rom9_4", -1, -1],
    ["marys house", "marys house", True, "land",
        "rom9_3", -1, -1],
    ["arena tree north", "arena tree north", False, "land",
        "rom9_5", -1, -1],
    ["arena tree west", "arena tree west", False, "land",
        "rom9_5", -1, -1],
    ["arena main", "arena main", False, "land",
        "rom9_5", -1, -1],
    ["crowroom heart east", "crowroom", False, "land",
        "rom8_4", -1, -1],
    ["crowroom heart south", "crowroom", False, "land",
        "rom8_4", -1, -1],
    ["tree resident south", "tree resident", False, "land",
        "rom10_4", -1, -1],
    ["tree resident west", "tree resident", False, "land",
        "rom10_4", -1, -1],
    ["bridge switch lookout", "bridge switch lookout", True, "land",
        "rom10_5", -1, -1],
    ["bridge switch right", "bridge switch right", False, "land",
        "rom10_5", -1, -1],
    ["bridge switch left", "bridge switch left", False, "land",
        "rom10_5", -1, -1],
    ["bridge switch water", "bridge switch water", False, "water",
        "rom10_5", -1, -1],
    ["bridge right north", "bridge right", False, "land",
        "rom10_6", -1, -1],
    ["bridge right east", "bridge right", False, "land",
        "rom10_6", -1, -1],
    ["bridge right south", "bridge right", False, "land",
        "rom10_6", -1, -1],
    ["bridge left north", "bridge left", False, "land",
        "rom10_6", -1, -1],
    ["bridge left south", "bridge left", False, "land",
        "rom10_6", -1, -1],
    ["bridge left west", "bridge left", False, "land",
        "rom10_6", -1, -1],
    ["bridge water north", "bridge water", False, "water",
        "rom10_6", -1, -1],
    ["bridge water south", "bridge water", False, "water",
        "rom10_6", -1, -1],
    ["hotel outside north", "hotel outside", False, "land",
        "rom9_6", -1, -1],
    ["hotel outside east", "hotel outside", False, "land",
        "rom9_6", -1, -1],
    ["hotel outside west", "hotel outside", False, "land",
        "rom9_6", -1, -1],
    ["hotel outside back entrance", "hotel outside", False, "land",
        "rom9_6", -1, -1],
    ["hotel outside front entrance", "hotel outside", False, "land",
        "rom9_6", -1, -1],
    ["mine entrance right north", "mine entrance right", False, "land",
        "rom10_7", -1, -1],
    ["mine entrance right door", "mine entrance right", False, "land",
        "rom10_7", -1, -1],
    ["mine entrance left north", "mine entrance left", False, "land",
        "rom10_7", -1, -1],
    ["mine entrance left door", "mine entrance left", False, "land",
        "rom10_7", -1, -1],
    ["mine entrance river north", "mine entrance river", False, "water",
        "rom10_7", -1, -1],
    ["mine entrance river south", "mine entrance river", False, "water",
        "rom10_7", -1, -1],
    ["poison river corner north", "poison river corner", False, "water",
        "rom10_8", -1, -1],
    ["poison river corner south", "poison river corner", False, "water",
        "rom10_8", -1, -1],
    ["factory reception main south", "factory reception main", False, "land",
        "rom11_6", -1, -1],
    ["factory reception main west", "factory reception main", False, "land",
        "rom11_6", -1, -1],
    ["factory reception east", "factory reception east", False, "land",
        "rom11_6", -1, -1],
    ["factory queue", "factory queue", True, "land",
        "rom11_7", -1, -1],
    ["factory cooler west", "factory cooler west", False, "land",
        "rom12_6", -1, -1],
    ["factory cooler east", "factory cooler east", False, "land",
        "rom12_6", -1, -1],
    ["factory cooler south", "factory cooler east", False, "land",
        "rom12_6", -1, -1],
    ["factory toilet south", "factory toilet", False, "land",
        "rom13_6", -1, -1],
    ["factory toilet west", "factory toilet", False, "land",
        "rom13_6", -1, -1],
    ["factory central north", "factory central", False, "land",
        "rom12_7", -1, -1],
    ["factory central south", "factory central", False, "land",
        "rom12_7", -1, -1],
    ["factory central door", "factory central", False, "land",
        "rom12_7", -1, -1],
    ["factory drill north", "factory drill", False, "land",
        "rom12_8", -1, -1],
    ["factory drill south", "factory drill", False, "land",
        "rom12_8", -1, -1],
    ["factory loading upper north", "factory loading upper", False, "land",
        "rom13_7", -1, -1],
    ["factory loading upper east", "factory loading upper", False, "land",
        "rom13_7", -1, -1],
    ["factory loading upper south", "factory loading upper", False, "land",
        "rom13_7", -1, -1],
    ["factory loading upper door", "factory loading upper", False, "land",
        "rom13_7", -1, -1],
    ["factory loading lower main", "factory loading lower main", False, "land",
        "rom13_8", -1, -1],
    ["factory loading lower shortcut", "factory loading lower shortcut", False, "land",
        "rom13_8", -1, -1],
    ["factory loading deadend", "factory loading deadend", True, "land",
        "rom14_7", -1, -1],
    ["factory loading desert north", "factory loading desert", True, "land",
        "rom14_7", -1, -1],
    ["factory loading desert east", "factory loading desert", True, "land",
        "rom14_7", -1, -1],
    ["shoe shop outside south", "shoe shop outside", False, "land",
        "rom14_8", -1, -1],
    ["shoe shop outside door", "shoe shop outside", False, "land",
        "rom14_8", -1, -1],
    ["shoe shop shortcut", "shoe shop shortcut", False, "land",
        "rom14_8", -1, -1],
    ["temple outside north", "temple outside", False, "land",
        "rom14_10", -1, -1],
    ["temple outside east", "temple outside", False, "land",
        "rom14_10", -1, -1],
    ["temple outside south", "temple outside", False, "land",
        "rom14_10", -1, -1],
    ["temple outside west", "temple outside", False, "land",
        "rom14_10", -1, -1],
    ["temple outside door", "temple outside", False, "land",
        "rom14_10", -1, -1],
    ["desert RV main east", "desert RV main", False, "land",
        "rom13_9", -1, -1],
    ["desert RV main south", "desert RV main", False, "land",
        "rom13_9", -1, -1],
    ["desert RV main west", "desert RV main", False, "land",
        "rom13_9", -1, -1],
    ["desert RV main door", "desert RV main", False, "land",
        "rom13_9", -1, -1],
    ["desert RV corner east", "desert RV corner", False, "land",
        "rom13_9", -1, -1],
    ["desert RV corner south", "desert RV corner", False, "land",
        "rom13_9", -1, -1],
    ["desert right cliffs north", "desert right cliffs", False, "land",
        "rom14_9", -1, -1],
    ["desert right cliffs east", "desert right cliffs", False, "land",
        "rom14_9", -1, -1],
    ["desert right cliffs south", "desert right cliffs", False, "land",
        "rom14_9", -1, -1],
    ["desert right cliffs upper west", "desert right cliffs", False, "land",
        "rom14_9", -1, -1],
    ["desert right cliffs lower west", "desert right cliffs", False, "land",
        "rom14_9", -1, -1],
    ["desert left cliffs upper north", "desert left cliffs", False, "land",
        "rom13_10", -1, -1],
    ["desert left cliffs lower north", "desert left cliffs", False, "land",
        "rom13_10", -1, -1],
    ["desert left cliffs east", "desert left cliffs", False, "land",
        "rom13_10", -1, -1],
    ["desert left cliffs south", "desert left cliffs", False, "land",
        "rom13_10", -1, -1],
    ["desert left cliffs west", "desert left cliffs", False, "land",
        "rom13_10", -1, -1],

    ["Overworld wet01", "Overworld", False, "water",
        "rom7_7", -1, -1],
    ["Overworld wet02", "Overworld", False, "water",
        "rom7_8", -1, -1],
    ["Overworld wet03", "Overworld", False, "water",
        "rom7_8", -1, -1],
    ["Overworld wet04", "Overworld", False, "water",
        "rom6_9", -1, -1],
    ["Overworld wet05", "Overworld", False, "water",
        "rom6_10", -1, -1],
    ["Overworld wet06", "Overworld", False, "water",
        "rom6_11", -1, -1],
    ["Overworld wet07", "Overworld", False, "water",
        "rom7_12", -1, -1],
    ["Overworld wet08", "Overworld", False, "water",
        "rom8_12", -1, -1],
    ["Overworld wet09", "Overworld", False, "water",
        "rom9_12", -1, -1],
    ["Overworld wet10", "Overworld", False, "water",
        "rom10_12", -1, -1],
    ["Overworld wet11", "Overworld", False, "water",
        "rom11_12", -1, -1],
    ["Overworld wet12", "Overworld", False, "water",
        "rom12_12", -1, -1],
    ["Overworld island door", "Overworld", False, "land",
        "rom8_15", -1, -1],
    ["Overworld dry01", "Overworld", False, "land",
        "rom12_12", -1, -1],
    ["Overworld dry02", "Overworld", False, "land",
        "rom13_11", -1, -1],
    ["Overworld dry03", "Overworld", False, "land",
        "rom13_11", -1, -1],
    ["Overworld dry04", "Overworld", False, "land",
        "rom14_11", -1, -1],
    ["Overworld dry05", "Overworld", False, "land",
        "rom15_10", -1, -1],
    ["Overworld dry06", "Overworld", False, "land",
        "rom15_9", -1, -1],
    ["Overworld dry07", "Overworld", False, "land",
        "rom15_7", -1, -1],
    ["Overworld dry08", "Overworld", False, "land",
        "rom14_6", -1, -1],


    ["RV house", "RV house", True, "land",
        "hom13_9", -1, -1],
    ["shoe shop inside door", "shoe shop inside", False, "land",
        "hom14_8", -1, -1],
    ["shoe shop inside basement", "shoe shop inside", False, "land",
        "hom14_8", -1, -1],
    ["hotel reception door", "hotel reception", False, "land",
        "hom9_6", -1, -1],
    ["hotel reception stairs", "hotel reception", False, "land",
        "hom9_6", -1, -1],
    ["hotel backroom", "hotel backroom", True, "land",
        "hom9_6", -1, -1],
    ["camera house inside", "camera house inside", True, "land",
        "hom9_7", -1, -1],
    ["waterfall cave", "waterfall cave", True, "water",
        "hom10_9", -1, -1],
    ["dog house inside door", "dog house inside", False, "land",
        "hom10_10", -1, -1],
    ["dog house inside basement", "dog house inside", False, "land",
        "hom10_10", -1, -1],
    ["coffee shop inside", "coffee shop inside", True, "land",
        "hom8_10", -1, -1],
    ["lighthouse inside upper", "lighthouse inside", False, "land",
        "hom7_10", -1, -1],
    ["lighthouse inside lower", "lighthouse inside", False, "land",
        "hom7_11", -1, -1],
    ["island house door", "island house", False, "land",
        "hom8_15", -1, -1],
    ["island house basement", "island house", False, "land",
        "hom8_15", -1, -1],
    ["megasword upper south", "megasword upper", False, "land",
        "hom12_7", -1, -1], 
    ["megasword upper right", "megasword upper", False, "land",
        "hom12_7", -1, -1],
    ["megasword upper left", "megasword upper", False, "land",
        "hom12_7", -1, -1],
    ["megasword lower", "megasword lower", True, "land",
        "hom12_8", -1, -1],
    ["underground house", "underground house", True, "land",
        "hom10_8", -1, -1],

    ["glove inside", "glove inside", True, "land",
        "dun11_10", -1, -1],
    ["shoe shop downstairs door", "shoe shop downstairs", False, "land",
        "dun14_8", -1, -1],
    ["shoe shop downstairs teleport", "shoe shop downstairs", False, "land",
        "dun14_8", -1, -1],
    ["temple main north", "temple main", False, "land",
        "dun14_10", -1, -1],
    ["temple main east", "temple main", False, "land",
        "dun14_10", -1, -1],
    ["temple main south", "temple main", False, "land",
        "dun14_10", -1, -1],
    ["temple main west", "temple main", False, "land",
        "dun14_10", -1, -1],
    ["temple main door", "temple main", False, "land",
        "dun14_10", -1, -1],
    ["temple octopus main", "temple octopus", False, "land",
        "dun13_10", -1, -1],
    ["temple octopus north", "temple octopus", False, "land",
        "dun13_10", -1, -1],
    ["temple tentacle", "temple tentacle", True, "water",
        "dun13_9", -1, -1],
    ["temple heart", "temple heart", True, "land",
        "dun14_11", -1, -1],
    ["temple firebat test east", "temple firebat test", False, "land",
        "dun15_10", -1, -1],  # consider smushing together
    ["temple firebat test west", "temple firebat test", False, "land",
        "dun15_10", -1, -1],
    ["temple firebat chest", "temple firebat chest", True, "land",
        "dun16_10", -1, -1],
    ["temple coin test north", "temple coin test", False, "land",
        "dun14_9", -1, -1],
    ["temple coin test south", "temple coin test", False, "land",
        "dun14_9", -1, -1],
    ["temple coin chest", "temple coin chest", True, "land",
        "dun14_8", -1, -1],
    ["hotel room door", "hotel room", False, "land",
        "dun9_6", -1, -1],
    ["hotel room teleport", "hotel room", False, "land",
        "dun9_6", -1, -1],
    ["mine entrance path north", "mine entrance path", False, "land",
        "dun10_7", -1, -1],
    ["mine entrance path east", "mine entrance path", False, "land",
        "dun10_7", -1, -1],
    ["mine entrance bombs", "mine entrance bombs", False, "land",
        "dun10_7", -1, -1],
    ["mine entrance pipe", "mine entrance pipe", False, "land",
        "dun10_7", -1, -1],  # oneway
    ["mine main north", "mine main", False, "land",
        "dun11_7", -1, -1],
    ["mine main west upper", "mine main", False, "land",
        "dun11_7", -1, -1],
    ["mine main west lower", "mine main", False, "land",
        "dun11_7", -1, -1],
    ["mine main box", "mine main box", False, "land",
        "dun11_7", -1, -1],
    ["dog house basement shop", "dog house basement", False, "land",
        "dun10_10", -1, -1],  # g ate switch and/or oneway
    ["dog house basement stairs", "dog house basement", False, "land",
        "dun10_10", -1, -1],
    ["dog house basement teleporter", "dog house basement", False, "land",
        "dun10_10", -1, -1],  # gate switch and/or oneway
    ["dog house basement hotel", "dog house basement", False, "land",
        "dun10_10", -1, -1],  # gate switch and/or oneway
    ["snake east upper", "snake east", False, "land",
        "dun10_9", -1, -1],
    ["snake east lower", "snake east", False, "land",
        "dun10_9", -1, -1],
    ["snake west", "snake west", True, "land",
        "dun9_9", -1, -1],
    ["sewer main right north", "sewer main right", False, "land",
        "dun8_10", -1, -1],
    ["sewer main right door", "sewer main right", False, "land",
        "dun8_10", -1, -1],
    ["sewer main left", "sewer main left", False, "water",
        "dun8_10", -1, -1],
    ["sewer bat arena north", "sewer bat arena", False, "land",
        "dun8_9", -1, -1],
    ["sewer bat arena south", "sewer bat arena", False, "land",
        "dun8_9", -1, -1],
    ["sewer bat gate", "sewer bat gate", False, "land",
        "dun8_9", -1, -1],  # oneway
    ["sewer upper door", "sewer upper", False, "land",
        "dun8_8", -1, -1],
    ["sewer upper south", "sewer upper", False, "land",
        "dun8_8", -1, -1],
    ["sewer tentacle", "sewer tentacle", True, "land",
        "dun7_10", -1, -1],
    ["island teleporter tile", "island teleporter", False, "land",
        "dun8_15", -1, -1],
    ["island teleporter east", "island teleporter", False, "land",
        "dun8_15", -1, -1],
    ["island teleporter south", "island teleporter", False, "land",
        "dun8_15", -1, -1],
    ["submarine east", "submarine", False, "land",
        "dun9_15", -1, -1],
    ["submarine west", "submarine", False, "land",
        "dun9_15", -1, -1],
    ["teleporter switch1", "teleporter switch1", True, "land",
        "dun11_15", -1, -1],  # gate
    ["teleporter maze east", "teleporter maze", False, "land",
        "dun10_15", -1, -1],
    ["teleporter maze south", "teleporter maze", False, "land",
        "dun10_15", -1, -1],
    ["teleporter maze west", "teleporter maze", False, "land",
        "dun10_15", -1, -1],
    ["teleporter tentacle", "teleporter tentacle", True, "land",
        "dun10_16", -1, -1],
    ["grinder south", "grinder south", False, "land",
        "dun11_6", -1, -1],
    ["grinder east", "grinder east", False, "land",
        "dun11_6", -1, -1],
    ["factory machine generator", "factory machine generator", False, "land",
        "dun12_6", -1, -1],
    ["factory machine catwalk east", "factory machine catwalk", False, "land",
        "dun12_6", -1, -1],
    ["factory machine catwalk west", "factory machine catwalk", False, "land",
        "dun12_6", -1, -1],
    ["factory switch test west", "factory switch test", False, "land",
        "dun13_6", -1, -1],
    ["factory switch test south", "factory switch test", False, "land",
        "dun13_6", -1, -1],
    ["factory mega entrance north", "factory mega entrance", False, "land",
        "dun12_7", -1, -1],  # consider lock and key shenanagins
    ["factory mega entrance door", "factory mega entrance", False, "land",
        "dun12_7", -1, -1],
    ["factory mega entrance right", "factory mega entrance", False, "land",
        "dun12_7", -1, -1],
    ["factory mega entrance left", "factory mega entrance", False, "land",
        "dun12_7", -1, -1],
    ["factory snakehall north", "factory snakehall", False, "land",
        "dun13_7", -1, -1],
    ["factory snakehall south", "factory snakehall", False, "land",
        "dun13_7", -1, -1],
    ["miner chest belts", "miner chest belts", False, "land",
        "dun11_8", -1, -1],
    ["miner chest pipe entrance", "miner chest pipe entrance", False, "land",
        "dun11_8", -1, -1],
    ["miner chest pipe L south", "miner chest pipe L", False, "land",
        "dun11_8", -1, -1],
    ["miner chest pipe L west", "miner chest pipe L", False, "land",
        "dun11_8", -1, -1],
    ["trophy pipe hall right", "trophy pipe hall", False, "land",
        "dun11_9", -1, -1],
    ["trophy pipe hall left", "trophy pipe hall", False, "land",
        "dun11_9", -1, -1],
    ["tent room main right", "tent room main", False, "land",
        "dun10_8", -1, -1],
    ["tent room main left", "tent room main", False, "land",
        "dun10_8", -1, -1],
    ["tent room pipe O", "tent room pipe O", True, "land",
        "dun10_8", -1, -1],
    ["tent room pipe I right", "tent room pipe I", False, "land",
        "dun10_8", -1, -1],
    ["tent room pipe I left", "tent room pipe I", False, "land",
        "dun10_8", -1, -1],
    ["trophy maze lower main north right", "trophy maze lower main", False, "land",
        "dun9_8", -1, -1],
    ["trophy maze lower main north left", "trophy maze lower main", False, "land",
        "dun9_8", -1, -1],
    ["trophy maze lower main east right", "trophy maze lower main", False, "land",
        "dun9_8", -1, -1],
    ["trophy maze lower main east left", "trophy maze lower main", False, "land",
        "dun9_8", -1, -1],
    ["trophy maze lower hall left", "trophy maze lower hall", False, "land",
        "dun9_8", -1, -1],
    ["trophy maze lower hall right", "trophy maze lower hall", False, "land",
        "dun9_8", -1, -1],
    ["trophy maze upper main right", "trophy maze upper main", False, "land",
        "dun9_7", -1, -1],
    ["trophy maze upper main left", "trophy maze upper main", False, "land",
        "dun9_7", -1, -1],
    ["trophy maze upper hall south", "trophy maze upper hall", False, "land",
        "dun9_7", -1, -1],
    ["trophy maze upper hall west", "trophy maze upper hall", False, "land",
        "dun9_7", -1, -1],
    ["trophy maze deadend", "trophy maze deadend", True, "land",
        "dun8_7", -1, -1],
    ["trophy room", "trophy room", True, "land",
        "rom11_8", -1, -1],
]


def minit_get_target_groups(group: str) -> list[str]:
    # if self.options.unmatched_room_rando:
    #     return ["land", "water"]
    match group:
        case "land":
            return ["land"]
        case "water":
            return ["water"]
